<?php
// ============================================================
//  Security Scanner — Config
//  Place ABOVE public_html — NEVER inside webroot.
//  Path: /var/www/scanner/config.php
//
//  Run setup.php ONCE from CLI to generate all values:
//    php /var/www/scanner/setup.php
//  Then delete setup.php immediately after.
// ============================================================

// ── Authentication — generated by setup.php ──────────────────
//
//  HOW THE PEPPER SYSTEM WORKS:
//  1. A random 64-char pepper is generated and stored here.
//  2. Login: HMAC-SHA256(email, pepper) is compared to AUTH_EMAIL_HMAC.
//     HMAC-SHA256(password, pepper) is run through bcrypt verify.
//  3. If an attacker reads this file, they have the hash AND the pepper —
//     but bcrypt cost-13 still makes cracking extremely slow.
//  4. If they get ONLY the hash (e.g. from a backup), they can't crack it
//     without also knowing the pepper — hashcat is useless without it.
//
define('AUTH_PEPPER',          '');   // php -r "echo bin2hex(random_bytes(32));"
define('AUTH_EMAIL_HMAC',      '');   // hash_hmac('sha256', strtolower($email), AUTH_PEPPER)
define('SCANNER_PASSWORD_HASH','');   // password_hash(hash_hmac('sha256',$pass,AUTH_PEPPER), PASSWORD_BCRYPT,['cost'=>13])

// ── Session ───────────────────────────────────────────────────
define('SESSION_TIMEOUT', 7200);      // 2 hours inactivity → auto-logout + token destruction
define('SESSION_NAME',    '_s');      // Non-default session cookie name (not PHPSESSID)

// ── Rate limiting ─────────────────────────────────────────────
// Lock out an IP for 15 min after 5 failed login attempts.
// File must be writable by www-data, stored above webroot.
define('RATE_LIMIT_FILE', __DIR__ . '/rate_limits.json');

// ── Source directory ──────────────────────────────────────────
// API handler files. In production move these ABOVE webroot into
// /var/www/scanner/src/ so they are never directly HTTP-accessible.
// .htaccess also blocks direct .php access as a second layer.
define('SRC_DIR', __DIR__ . '/public_html/api/');

// ── API Keys (free tiers) ─────────────────────────────────────
define('VT_API_KEY',     '');   // virustotal.com/gui/join-us
define('ABUSEIPDB_KEY',  '');   // abuseipdb.com/register
define('GSB_API_KEY',    '');   // console.cloud.google.com → Safe Browsing API
define('SHODAN_API_KEY', '');   // account.shodan.io/register

// ── Paths ─────────────────────────────────────────────────────
define('UPLOAD_TEMP_DIR', '/tmp/scanner_uploads/');
define('LOG_DIR',         __DIR__ . '/logs/');
define('PDFID_PATH',      '/opt/pdfid/pdfid.py');
define('CLAMSCAN_PATH',   '/usr/bin/clamscan');

// ── Scanner limits ────────────────────────────────────────────
define('MAX_UPLOAD_BYTES',  25 * 1024 * 1024);
define('MAX_CRAWL_DEPTH',   3);
define('MAX_CRAWL_URLS',    200);
define('HTTP_TIMEOUT',      10);
