<?php
// ============================================================
//  Security Scanner — One-time setup script
//  Run from CLI ONLY:  php setup.php
//  DELETE this file immediately after running.
// ============================================================

if (php_sapi_name() !== 'cli') {
    http_response_code(403);
    exit("This script must be run from the command line only.\n");
}

echo "\n";
echo "==============================================\n";
echo "  Security Scanner — First-time Setup\n";
echo "==============================================\n\n";
echo "This will generate config.php with your credentials.\n";
echo "Run once, then DELETE this file.\n\n";

// ── Prompt helpers ────────────────────────────────────────────
function prompt(string $label, bool $hidden = false): string {
    echo $label . ': ';
    if ($hidden && PHP_OS_FAMILY !== 'Windows') {
        system('stty -echo');
        $val = trim(fgets(STDIN));
        system('stty echo');
        echo "\n";
    } else {
        $val = trim(fgets(STDIN));
    }
    return $val;
}

function abort(string $msg): void {
    echo "\n[ERROR] $msg\n\n";
    exit(1);
}

// ── Collect email ─────────────────────────────────────────────
$email = prompt('Admin email address');
if (!filter_var($email, FILTER_VALIDATE_EMAIL)) abort('Invalid email address.');
$email = strtolower(trim($email));

// ── Collect password ──────────────────────────────────────────
$pass1 = prompt('Admin password (hidden)', true);
if (strlen($pass1) < 16) abort('Password must be at least 16 characters.');

$pass2 = prompt('Confirm password (hidden)', true);
if ($pass1 !== $pass2) abort('Passwords do not match.');

// ── Collect API keys (optional) ──────────────────────────────
echo "\nOptional API keys — press Enter to skip:\n";
$vt_key      = prompt('  VirusTotal API key');
$abuse_key   = prompt('  AbuseIPDB API key');
$gsb_key     = prompt('  Google Safe Browsing API key');
$shodan_key  = prompt('  Shodan API key');

// ── Generate cryptographic values ────────────────────────────
echo "\nGenerating credentials...\n";

$pepper     = bin2hex(random_bytes(32));                               // 64-char hex
$email_hmac = hash_hmac('sha256', $email, $pepper);                   // keyed hash of email
$pass_hmac  = hash_hmac('sha256', $pass1, $pepper);                   // keyed hash of password
$pass_hash  = password_hash($pass_hmac, PASSWORD_BCRYPT, ['cost' => 13]); // bcrypt cost-13 (~1s)
$sess_name  = '_' . substr(bin2hex(random_bytes(3)), 0, 5);           // e.g. _a3f8d

// ── Paths ─────────────────────────────────────────────────────
$config_dir  = __DIR__;
$log_dir     = $config_dir . '/logs/';
$rl_file     = $config_dir . '/rate_limits.json';
$src_dir     = $config_dir . '/public_html/api/';

// ── Write config.php ─────────────────────────────────────────
$out_path = $config_dir . '/config.php';

if (file_exists($out_path)) {
    $overwrite = prompt("\nconfig.php already exists. Overwrite? (yes/no)");
    if (strtolower($overwrite) !== 'yes') abort('Setup cancelled — existing config preserved.');
}

@mkdir($log_dir, 0750, true);

$config = <<<PHP
<?php
// Generated by setup.php on {$_SERVER['REQUEST_TIME_FLOAT'] ? date('Y-m-d H:i:s') : date('Y-m-d H:i:s')}
// DELETE setup.php now that this exists.

// ── Authentication ────────────────────────────────────────────
define('AUTH_PEPPER',           '{$pepper}');
define('AUTH_EMAIL_HMAC',       '{$email_hmac}');
define('SCANNER_PASSWORD_HASH', '{$pass_hash}');

// ── Session ───────────────────────────────────────────────────
define('SESSION_TIMEOUT', 7200);
define('SESSION_NAME',    '{$sess_name}');

// ── Rate limiting ─────────────────────────────────────────────
define('RATE_LIMIT_FILE', __DIR__ . '/rate_limits.json');

// ── Source directory (API handlers) ──────────────────────────
define('SRC_DIR', __DIR__ . '/public_html/api/');

// ── API Keys ──────────────────────────────────────────────────
define('VT_API_KEY',     '{$vt_key}');
define('ABUSEIPDB_KEY',  '{$abuse_key}');
define('GSB_API_KEY',    '{$gsb_key}');
define('SHODAN_API_KEY', '{$shodan_key}');

// ── Paths ─────────────────────────────────────────────────────
define('UPLOAD_TEMP_DIR', '/tmp/scanner_uploads/');
define('LOG_DIR',         __DIR__ . '/logs/');
define('PDFID_PATH',      '/opt/pdfid/pdfid.py');
define('CLAMSCAN_PATH',   '/usr/bin/clamscan');

// ── Scanner limits ────────────────────────────────────────────
define('MAX_UPLOAD_BYTES',  25 * 1024 * 1024);
define('MAX_CRAWL_DEPTH',   3);
define('MAX_CRAWL_URLS',    200);
define('HTTP_TIMEOUT',      10);
PHP;

if (file_put_contents($out_path, $config, LOCK_EX) === false) {
    abort("Could not write config.php to {$out_path}. Check directory permissions.");
}
chmod($out_path, 0640); // owner rw, group r, other none

echo "\n==============================================\n";
echo "  Setup complete!\n";
echo "==============================================\n\n";
echo "  config.php written to: {$out_path}\n";
echo "  Permissions set to 0640 (owner+group read only)\n\n";
echo "  !! DELETE THIS FILE NOW:\n";
echo "     rm " . __FILE__ . "\n\n";
echo "  Log directory created: {$log_dir}\n";
echo "  Session cookie name:   {$sess_name}\n\n";
echo "  Login credentials:\n";
echo "    Email:    {$email}\n";
echo "    Password: (as entered — not shown again)\n\n";
